from langchain_core.prompts import PromptTemplate # type: ignore
from graph_state import validator_format_instructions

def get_validator_system_prompt():
    prompt = PromptTemplate.from_template(
        """
        You are a Validator agent responsible for assessing the accuracy, completeness, and relevance of a response within a structured workflow.

        Here is the user query: "{user_query}"  
        The previous node type was: "{previous_node_type}"  
        The response from the previous node was:  
        "{previous_node_response}"

        Evaluate the response based on the following criteria:
        1. **Relevance**: Does the response directly address the user query?
        2. **Accuracy**: Is the response factually correct and coherent?
        3. **Source Reliability**: If sourced externally (RAG or Crawler), are references reliable and properly integrated?
        4. **LLM Quality**: If generated by LLM, does the response avoid hallucination and align with expected knowledge?

        If the response meets all criteria, confirm validation and allow workflow completion.  
        If the response fails any criteria, provide a brief reason and instruct rerouting to the Supervisor node for refinement.

        
        Format Instructions: {format_instructions}
        """
    )

    prompt = prompt.partial(format_instructions=validator_format_instructions)

    return prompt